### PR TITLE
Use Z3 5.0.0

### LINKED ISSUE #69: Use a newer version of `z3`
Currently, we ship versions 4.8.8 and 4.8.14 of Z3 with `what4-solvers` snapshots, but these versions are quite old at this point. Even worse, we have observed these Z3 versions going into infinite loops on certain programs, but newer versions of Z3 handle them without issue. We should look into upgrading the version of Z3 that is offered with `what4-solvers` to address this.

Before making this change, we should convince ourselves that upgrading Z3 will not introduce any performance regressions in import Cryptol or SAW test cases.

### PR DESCRIPTION
**Pull request by RyanGlScott**
Fixes #69.

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Alas, Z3-5.0.0 fails to build on Ubuntu 22.04. See [this failing CI job](https://github.com/GaloisInc/what4-solvers/actions/runs/29583354338/job/87894189251?pr=100#step:7:345):

```
/usr/bin/c++ -D_EXTERNAL_RELEASE -D_MP_INTERNAL -I/__w/what4-solvers/what4-solvers/repos/z3/build/src -I/__w/what4-solvers/what4-solvers/repos/z3/src -Werror=odr  -Werror=return-type  -O3 -DNDEBUG -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -std=gnu++20 -MD -MT src/ast/CMakeFiles/ast.dir/array_decl_plugin.cpp.o -MF src/ast/CMakeFiles/ast.dir/array_decl_plugin.cpp.o.d -o src/ast/CMakeFiles/ast.dir/array_decl_plugin.cpp.o -c /__w/what4-solvers/what4-solvers/repos/z3/src/ast/array_decl_plugin.cpp
/__w/what4-solvers/what4-solvers/repos/z3/src/ast/array_decl_plugin.cpp:20:9: fatal error: format: No such file or directory
   20 | #include<format>
      |         ^~~~~~~~
```

And indeed, the [Z3 README](https://github.com/Z3Prover/z3/blob/8e3402b215a810a4154eb183a7dfc4e853eb2f52/README.md#building-z3-on-windows-using-visual-studio-command-prompt) now advertises that it requires C++20 in order to build, but the version of `g++` shipped with Ubuntu 22.04 is too old for C++20 support. Some possible next things to try:

1. Drop Ubuntu 22.04 support entirely. (This is likely a non-starter for a while longer yet.)
2. Figure out how to patch Z3-5.0.0 in order to make it build with older toolchains. (This would likely be a lot of work.)
3. Figure out how to install a newer C++ compiler on Ubuntu 22.04.
4. Backport the fix from https://github.com/Z3Prover/z3/commit/038b367d6 to an older version of Z3.

**Comment by RyanGlScott** [comment]
Actually, this isn't just an Ubuntu 22.04 problem: it also affects `redhat/ubi9:latest`. See [this failing CI job](https://github.com/GaloisInc/what4-solvers/actions/runs/29583354338/job/87894189115?pr=100). Ugh.

**Comment by RyanGlScott** [comment]
@sauclovian-g and I discussed this, and we concluded that backporting the fix from https://github.com/Z3Prover/z3/commit/038b367d6 to an older version of Z3 was the best course of action. Trying to figure out which Z3 version introduced the C++20 dependency is somewhat tricky, but given that [this commit](https://github.com/Z3Prover/z3/commit/5cee19fa09555323f1b82baf8038cfdb858e6ee6) was introduced in Z3-4.15.4, I think we should first try Z3-4.15.3.

**Comment by podhrmic** [comment]
@RyanGlScott could I ask you to reconsider? It appears that a newer version of gcc can be installed fairly easily (with [mamba](https://askubuntu.com/a/1529025) or with [xpack](https://github.com/xpack-dev-tools/gcc-xpack) - arguably neither is particularly neat solution, but if it is just for compilation it may not matter). I haven't tested the redhat images yet.

The benefit would be that z3-5.0 presumably contains further bug fixes and improvements, so should be overall faster than 4.15.

EDIT: removed the incorrect Ubuntu:24.04 reference

**Comment by RyanGlScott** [comment]
I shied away from the idea of installing newer toolchains as I imagined this would be a complicated and fragile process. If you think that's not the case, then please do give your idea a try! (Feel free to push to the branch I'm using.)

**Comment by RyanGlScott** [comment]
There are also some linkers errors on the [Windows CI job](https://github.com/GaloisInc/what4-solvers/actions/runs/29583354338/job/88498473877?pr=100#step:11:1471) that I've never seen before on older Z3s. I've opened https://github.com/Z3Prover/z3/issues/10171 about this upstream.

In the meantime, I've worked around this on the `what4-solvers` side in https://github.com/GaloisInc/what4-solvers/pull/100/commits/2f908355dedbbe574e1e9bbc408a4e8a5d71902c.

**Comment by podhrmic** [comment]
Current status:
* `yices` fails on redhat because the newer toolchain uses `-Werror=maybe-uninitialized` - we need to revert it back to `-Warn`
* z3 on Ubuntu 22.04 - fails tests, because running the new z3 requires `GLIBCXX_3.4.32` which is not available. A new `libstdc++.so.6` can be vendored in (xpack already has it), but it means you have to patch every single `ubuntu:22.04` docker image that uses `z3-5.0`. Since 22.04 is EOL in June 2027, maybe it is reasonable to start discontinuing it? And ship z3 with a warning and instructions how to patch your OS with newer libstdc++

**Comment by RyanGlScott** [comment]
> `yices` fails on redhat because the newer toolchain uses `-Werror=maybe-uninitialized` - we need to revert it back to `-Warn`

Ugh, I really wish that `libpoly` didn't error on warnings by default. (This isn't even the first time this has caused us problems---see https://github.com/SRI-CSL/libpoly/issues/67.) It might be worth filing an issue with `libpoly` upstream about the particular `-Werror=maybe-uninitialized` error seen here, as it would be nice to fix this.

In the meantime, we'll have to patch around the issue some way, either by fixing the `-Werror=maybe-uninitialized` error or by downgrading `-Werror` to `-Wwarn`.

> z3 on Ubuntu 22.04 - fails tests, because running the new z3 requires `GLIBCXX_3.4.32` which is not available. A new `libstdc++.so.6` can be vendored in (xpack already has it), but it means you have to patch every single `ubuntu:22.04` docker image that uses `z3-5.0`.

Ugh.

> Since 22.04 is EOL in June 2027, maybe it is reasonable to start discontinuing it?

Discontinuing Ubuntu 22.04 is a non-starter right now, as we still have users who depend on the 22.04 versions of the tools. That being said, it is only a matter of time before GitHub deprecates (and eventually removes) its 22.04 CI runners, so we will have to drop 22.04 at some point in the future.

> And ship z3 with a warning and instructions how to patch your OS with newer libstdc++

I'd really prefer not to get into the business of requiring users to patch their OS. One of the main selling points of `what4-solvers` is to have easy-to-download versions of the tools that work on popular OSes without requiring one to perform brain surgery afterwards in order to get the tools to run. In my view, needing to install a newer `libstdc++` inches us closer to brain surgery.

**Comment by podhrmic** [comment]
Looks like this is enough to get `libpoly` to compile without warnings so I can fix the `yices` error:

```
diff --git a/src/number/value.c b/src/number/value.c
index 62f45fc..952fa4c 100644
--- a/src/number/value.c
+++ b/src/number/value.c
@@ -1252,8 +1252,8 @@ void lp_value_neg(lp_value_t* neg, const lp_value_t* a) {
 void lp_value_mul(lp_value_t* mul, const lp_value_t* a, const lp_value_t* b) {

   lp_value_t a_new, b_new;
-  const lp_value_t *a_to_use;
-  const lp_value_t *b_to_use;
+  const lp_value_t *a_to_use = {};
+  const lp_value_t *b_to_use = {};

   // Check for infinities
   if (lp_value_is_infinity(a) || lp_value_is_infinity(b)) {
```

Interestingly the issue manifests only on `ubi10/latest-x64`

**Comment by podhrmic** [comment]
Pending the running tests, this PR is now building and running the new z3 across all supported platforms. Updating ubi9 to ubi10 was simple, ubuntu 22.04 required one OS library to be updated (which may or may not be OK).

We can either leave as is and merge when ubuntu:22.04 runners are deprecated (September/April - see [the github announcement](https://github.com/actions/runner-images/issues/14254)), or when Ubuntu 22 reached its EOL (July 2027)

**Comment by sauclovian-g** [comment]
Using more than one libstdc++ major version at a time is a bad idea. Unless nothing else that z3 links with uses C++, it will end up linked to both versions; then because of the (broken) way ELF shared libraries do runtime linking, you'll get calls into the wrong version and demons fly out of your nose.

_If_ z3 links to nothing using the older libstdc++, building it like this may work, but it's important to either statically link it to its own libstdc++ or make sure the variant libstdc++.so image goes in a place that nothing else can use by accident.

Patching the OS install is the wrong approach...

**Comment by RyanGlScott** [comment]
I agree with @sauclovian-g. While it is somewhat impressive that we can get this to work at all, my fear is that the resulting user experience will be fragile unless users are very careful to avoid mixing up the two `libstdc++`s.

I'm certainly fine with parking this PR here until we drop support for Ubuntu 22.04.

File: patches/libpoly-gcc14-werror-uninitialized-variable.patch [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+--- a/src/number/value.c
++++ b/src/number/value.c
+@@ -1252,8 +1252,8 @@ void lp_value_neg(lp_value_t* neg, const lp_value_t* a) {
+ void lp_value_mul(lp_value_t* mul, const lp_value_t* a, const lp_value_t* b) {
+
+   lp_value_t a_new, b_new;
+-  const lp_value_t *a_to_use;
+-  const lp_value_t *b_to_use;
++  const lp_value_t *a_to_use = {0};
++  const lp_value_t *b_to_use = {0};
```
Comment (sauclovian-g) [inline patches/libpoly-gcc14-werror-uninitialized-variable.patch:12]: Surely these should be `NULL`? `{0}` is not (properly) a valid initializer for a pointer.

**Comment by sauclovian-g** [comment]
It looks reasonably possible to hack the build system to link statically against libstdc++. Whether that will work depends on (a) whether any of the other libs it links to use libstdc++ (that is not fundamentally a stopper but makes it a lot more complicated) and (b) whether it's legal to distribute the resulting binary, which I wouldn't venture to offer an opinion on.
